services:
  fast_api_app:
    build: .
    image: fast_api_app:latest
    container_name: fast_api_app
    restart: always
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_TTL=3600
    networks:
      - fast_api_app_network
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - fast_api_app
    networks:
      - fast_api_app_network

  redis:
    image: redis:latest
    container_name: redis_server
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - fast_api_app_network


  redisinsight:
    image: redis/redisinsight:latest
    container_name: redis_insight
    restart: always
    ports:
      - "5540:5540"
    volumes:
      - redisinsight_data:/data
    networks:
      - fast_api_app_network

volumes:
  redis_data:
  redisinsight_data:

networks:
  fast_api_app_network:
    driver: bridge